name: Build Workflow

run-name: 'Build Workflow'

on:
    push:
    pull_request:

env:
  MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ikmdev'
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4
          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: '21'
          - name: Maven Build
            if: github.ref == 'refs/heads/main'
            run: |
              mvn clean install \
                -s ${{env.MAVEN_SETTING}} \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality
          - name: Maven Build -- Feature Branch
            if: github.ref != 'refs/heads/main'
            run: |
              java --version
              mvn clean install \
                -s ${{env.MAVEN_SETTING}} \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -Denforcer.skip=true \
                -PcodeQuality
