name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/setup-java@v4
        with:
            java-version: '21'
            distribution: 'zulu'
          
      - name: Build IKMDEV Code
        uses: ikmdev/maven-clean-install-build-action@main
        with:
          branch_name: ${{env.BRANCH_NAME}}
      
      - name: Deploy Artifacts To Nexus
        if: github.repository_owner == 'ikmdev'
        uses: ikmdev/maven-nexus-deploy-action@main
        with:
          nexus_repo_id: "maven-snapshots"
          nexus_repo_password: ${{secrets.EC2_NEXUS_PASSWORD}}
  
  