name: Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:

env:
  MAVEN_SETTING: '/home/ec2-user/maven/.m2/settings.xml'
  BRANCH_NAME: ${{github.ref_name}}

jobs:
  build-job:
    name: Build Job
    runs-on: self-hosted
    if: github.repository_owner == 'ikmdev'
    steps:
          - name: Build IKMDEV Code
            uses: ikmdev/ikmdev-build-action@main
            with:
              branch_name: ${{env.BRANCH_NAME}}
        

  forked-repo-build-job:
    name: Forked Repo Build Job
    runs-on: ubuntu-latest
    if: github.repository_owner != 'ikmdev' || github.event.repository.fork == 'true'
    steps:
          - name: Checkout Code Repository
            uses: actions/checkout@v4

          - name: Setup Java
            uses: actions/setup-java@v4
            with:
              distribution: 'adopt'
              java-version: '21'
              
          - name: Maven Build
            if: env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master' 
            run: |
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality

          - name: Maven Build -- Feature Branch
            if: env.BRANCH_NAME != 'main' && env.BRANCH_NAME != 'master' 
            run: |
              java --version
              mvn clean install \
                --batch-mode \
                -e \
                -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                -PcodeQuality