name: Feature Branch Workflow

run-name: ${{inputs.action}} -- feature/${{inputs.branch_name}}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name without the "feature/" prefix'
        required: false
      action:
        description: 'Choose an action: Start or Finish'
        required: true
        type: choice
        options:
          - --Select--
          - Start
          - Finish
        default: --Select--

env:
  BRANCH_NAME: feature/${{inputs.branch_name}}
  TRIGGER_BRANCH_NAME: ${{github.ref_name}}

jobs:
  feature_branch_ci:
    name: "${{inputs.action}} Action"
    if: inputs.action != '--Select--' 
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Validate Branch Name Is Entered (Main/Master Branch)
        if: (github.ref_name == 'main' || github.ref_name == 'master') && inputs.branch_name == ''
        run: |
          echo "${{github.ref_name}}"
          echo "Default: ${{github.event.repository.default_branch}}"
          echo "Please enter Branch Name!"
          exit 1

      - name: Get Input Name
        run: |
          echo "Input: ${{inputs.branch_name}}"
          echo "Ref: ${{github.ref_name}}"
          exit 1

      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: "[${{inputs.action}}] Feature Branch CI"
        uses: ikmdev/maven-unique-feature-branch-action@master
        with:
          action: ${{inputs.action}}
          original_branch_name: ${{inputs.branch_name}}
          feature_branch_name: ${{env.BRANCH_NAME}}
          trigger_branch_name: ${{env.TRIGGER_BRANCH_NAME}}
          repository: ${{github.event.repository.name}}
          github_token: ${{secrets.GITHUB_TOKEN}}
  
        
