name: Feature Branch Workflow (NO PR)

run-name: ${{inputs.action}} -- feature/${{inputs.branch_name}}

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Enter the branch name without the "feature/" prefix'
        required: false
      action:
        description: 'Choose an action: Start or Finish'
        required: true
        type: choice
        options:
          - --Select--
          - Start
          - Finish
        default: --Select--

env:
  BRANCH_NAME: feature/${{inputs.branch_name}}
  TRIGGER_BRANCH_NAME: ${{}}

jobs:
  feature_branch_ci:
    name: "${{inputs.action}} Action"
    if: inputs.action != '--Select--' 
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - run: |
         echo ${{github.ref_name}}
         exit 1
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: "[${{inputs.action}}] Feature Branch CI"
        uses: ikmdev/maven-unique-feature-branch-action@master
        with:
          action: ${{inputs.action}}
          original_branch_name: ${{inputs.branch_name}}
          feature_branch_name: ${{env.BRANCH_NAME}}
          repository: ${{github.event.repository.name}}
          github_token: ${{secrets.GITHUB_TOKEN}}
  
        