name: Feature Branch Lifecycle Workflow

run-name: 'Build Feature Branch Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  workflow_dispatch:
    inputs:
      feature_action:
        description: 'Select which feature action to run'
        required: true
        default: 'start'
        type: choice
        options:
          - start
          - finish
          - resume
      branch_name:
        description: 'Enter the name of the branch to operate on (without feature/ prefix)'
        required: true

env:
    GH_TOKEN: "${{ github.token }}"
    IKMDEVOPS_PAT: "${{secrets.IKMDEVOPS_PAT_TOKEN}}"
    TRUNK_BRANCH: "main"
    BRANCH_NAME: "${{ github.event.inputs.branch_name }}"
    FEATURE_BRANCH: "feature/$BRANCH_NAME"
    PR_NUMBER: "${{ github.event.number }}"
    
jobs:
  start-feature:
    if: ${{ github.event.inputs.feature_action == 'start' }}
    runs-on: ubuntu-24.04
    name: Start Feature Job

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set Git user email and name
      - name: Set up Git config
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      # Check and add feature/ prefix to branch name if missing
      - name: Ensure feature/ prefix
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          if [[ $BRANCH_NAME != feature/* ]]; then
            FEATURE_BRANCH="feature/$BRANCH_NAME"
            echo "Renaming branch to $FEATURE_BRANCH"
            git branch -m "$FEATURE_BRANCH"
            git push origin -u "$FEATURE_BRANCH"
          else
            echo "Branch name already starts with feature/"
          fi

      - name: Check for existing PR
        run: |
          pr_exists=$(gh pr list --head ${{ github.event.inputs.branch_name }} --json number --jq '.[].number')
          if [ -n "$pr_exists" ]; then
            echo "Error: Pull Request already exists for branch ${{ github.event.inputs.branch_name }}."
            exit 1
          fi

      - name: Update Maven coordinates
        run: |
          VERSION="1.0.0-${{ github.event.inputs.branch_name }}-SNAPSHOT"
          mvn versions:set -DnewVersion=$VERSION
          mvn versions:commit
          git add pom.xml
          git commit -m "chore: update Maven coordinates to $VERSION"
          git pull origin HEAD
          git push -u origin HEAD

      - name: Create Draft PR
        run: |
          gh pr create --head "$FEATURE_BRANCH" --base main --title "Draft PR for $FEATURE_BRANCH" --body "This is a draft PR for $FEATURE_BRANCH" --draft

  
  finish-feature:
    if: ${{ github.event.inputs.feature_action == 'finish' }}
    runs-on: ubuntu-24.04
    name: Finish Feature Job

    steps:
      # Set Git user email and name
      - name: Set up Git config
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Find and Check PR State
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          pr_number=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[].number')
          if [ -z "$pr_number" ]; then
          echo "Error: No PR found for branch $BRANCH_NAME."
          exit 1
          fi
          pr_draft=$(gh pr view "$pr_number" --json isDraft --jq '.isDraft')
          if [ "$pr_draft" != "true" ]; then
          echo "Error: PR #$pr_number is not in draft state."
          exit 1
          fi

      - name: Set PR to Finish
        run: |
          gh pr ready "$pr_number"

      - name: Update Maven coordinates to default version
        run: |
          VERSION="1.0.0"
          mvn versions:set -DnewVersion=$VERSION
          mvn versions:commit
          git add pom.xml
          git commit -m "chore: set Maven coordinates to $VERSION"
          git pull origin HEAD
          git push -u origin HEAD


  resume-feature:
    if: ${{ github.event.inputs.feature_action == 'resume' }}
    runs-on: ubuntu-24.04
    name: Resume Feature Job

    steps:
      - name: Set up Git config
        run: |
          git config --global user.email "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Find and Check PR State
        run: |
          BRANCH_NAME="${{ github.event.inputs.branch_name }}"
          pr_number=$(gh pr list --head "$BRANCH_NAME" --json number --jq '.[].number')
          if [ -z "$pr_number" ]; then
            echo "Error: No PR found for branch $BRANCH_NAME."
            exit 1
          fi
          pr_state=$(gh pr view "$pr_number" --json state --jq '.state')
          if [ "$pr_state" != "CLOSED" ]; then
            echo "Error: PR #$pr_number is not in finished state (closed)."
            exit 1
          fi

      - name: Reopen and Set PR to Draft
        run: |
          gh pr reopen "$pr_number"
          gh pr edit "$pr_number" --draft

      - name: Update Maven coordinates to unique version
        run: |
          VERSION="1.0.0-${{ github.event.inputs.feature_branch }}-SNAPSHOT"
          mvn versions:set -DnewVersion=$VERSION
          mvn versions:commit
          git add pom.xml
          git commit -m "chore: revert Maven coordinates to $VERSION"
          git pull origin HEAD
          git push -u origin HEAD