name: Nexus Build Workflow

run-name: 'Build Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
    push:
    pull_request:
    workflow_dispatch:

env:
  BRANCH_NAME: ${{github.ref_name}}

jobs: 
  publish-artifacts:
      name: Publish Artifacts
      runs-on: ubuntu-24.04
      if: github.repository_owner == 'ikmdev'

      env:
        ARTIFACT_REPOSITORY_ID: "maven-snapshots"
        REPOSITORY_NAME: ${{github.repository}}
        BRANCH: "main"
        MAVEN_SETTINGS: '/home/runner/work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' 
        

      steps:  
        - name: Checkout Forked Code Repository
          uses: actions/checkout@v4

        - name: Setup Java
          uses: actions/setup-java@v4
          with:
            distribution: 'zulu'
            java-version: '21'
      
         
        - name: Maven Settings File
          uses: whelk-io/maven-settings-xml-action@v22
          with:
            servers: '[{"id": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}", "username": "${{vars.EC2_NEXUS_USERNAME}}", "password": ${{secrets.EC2_NEXUS_PASSWORD}}}]'
            profiles: '[{"id": "inject-application-properties". "properties": {"altDeploymentRepository": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}::${{ vars.EC2_NEXUS_URL }}/repository/maven-snapshots"}}]'
            active_profiles: '["inject-application-properties"]' 
            # servers: > 
            #               [
            #                 {
            #                   "id": "nexus"
            #                 },
            #                 {
            #                   "id": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}",
            #                   "username": "${{ vars.EC2_NEXUS_USERNAME }}",
            #                   "password": "${{ secrets.EC2_NEXUS_PASSWORD}}"
            #                 }
            #               ] 
            #   profiles: >
            #               [{
            #                   "id": "inject-application-properties",
            #                   "properties": {
            #                       "altDeploymentRepository": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}::${{ vars.EC2_NEXUS_URL }}/repository/maven-snapshots"
            #                   }
            #               }]
            #   active_profiles: > 
            #               [
            #                 "inject-application-properties"
            #               ]
              output_file: .m2/settings.xml


        - name: Deploy To Nexus
          run: |
               mvn deploy \
                  --batch-mode \
                  -e \
                  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                  -DskipTests \
                  -DskipITs \
                  -Dmaven.main.skip \
                  -Dmaven.test.skip \
                  -Dmaven.wagon.http.ssl.insecure=true \
                  -Dmaven.wagon.http.ssl.allowall=true \
                  -s ${{env.MAVEN_SETTINGS}} \
                  -DrepositoryId='${{env.ARTIFACT_REPOSITORY_ID}}' 

     