name: Feature Branch Lifecycle Workflow

run-name: 'Feature Workflow -- ${{ github.head_ref || github.ref_name }}'

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select an action: start, finish, or resume'
        required: true
        type: choice
        options:
          - start
          - finish
          - resume
      branch_name:
        description: 'Enter the feature branch name (without "feature/")'
        required: true

env:
  DEFAULT_VERSION: '1.0.0'
  UNIQUE_VERSION: '1.0.0-unique'

jobs:
  start:
    if: ${{ github.event.inputs.action == 'start' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Variables
        id: vars
        run: |
          echo "BRANCH_NAME=feature/${{ github.event.inputs.branch_name }}" >> $GITHUB_OUTPUT

      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.IKMDEVOPS_PAT_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Update Maven Coordinates
        run: |
          echo "Updating Maven coordinates..."
          sed -i 's|<version>.*</version>|<version>'$UNIQUE_VERSION'</version>|' pom.xml

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git checkout -b "${{ steps.vars.outputs.BRANCH_NAME }}"
          git add .
          git commit -m "Update Maven coordinates for start"
          git push origin "${{ steps.vars.outputs.BRANCH_NAME }}"

      - name: Create Pull Request (Start)
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              owner: '${{ github.event.repository.parent.owner.login }}',
              repo: '${{ github.event.repository.parent.name }}',
              title: 'Feature: ${{ github.event.inputs.branch_name }}',
              head: '${{ github.actor }}:${{ steps.vars.outputs.BRANCH_NAME }}',
              base: 'main',
              body: 'This PR introduces feature ${{ github.event.inputs.branch_name }}.',
              draft: true
            });
            console.log('Pull request created.');

  finish:
    if: ${{ github.event.inputs.action == 'finish' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Variables
        id: vars
        run: |
          echo "BRANCH_NAME=feature/${{ github.event.inputs.branch_name }}" >> $GITHUB_OUTPUT

      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.IKMDEVOPS_PAT_TOKEN }}
          ref: ${{ steps.vars.outputs.BRANCH_NAME }}
          fetch-depth: 0

      - name: Update Maven Coordinates
        run: |
          echo "Updating Maven coordinates..."
          sed -i 's|<version>.*</version>|<version>'$DEFAULT_VERSION'</version>|' pom.xml

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add .
          git commit -m "Update Maven coordinates for finish"
          git push origin "${{ steps.vars.outputs.BRANCH_NAME }}"

      - name: Change Pull Request State to Ready
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: '${{ github.event.repository.parent.owner.login }}',
              repo: '${{ github.event.repository.parent.name }}',
              head: '${{ github.actor }}:${{ steps.vars.outputs.BRANCH_NAME }}',
              state: 'open'
            });
            if (pulls.length > 0) {
              const prNumber = pulls[0].number;
              await github.rest.pulls.update({
                owner: '${{ github.event.repository.parent.owner.login }}',
                repo: '${{ github.event.repository.parent.name }}',
                pull_number: prNumber,
                draft: false
              });
              console.log(`Pull request #${prNumber} marked as ready for review.`);
            } else {
              console.log('No open pull request found.');
            }

  resume:
    if: ${{ github.event.inputs.action == 'resume' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Variables
        id: vars
        run: |
          echo "BRANCH_NAME=feature/${{ github.event.inputs.branch_name }}" >> $GITHUB_OUTPUT

      - name: Checkout Forked Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.IKMDEVOPS_PAT_TOKEN }}
          ref: ${{ steps.vars.outputs.BRANCH_NAME }}
          fetch-depth: 0

      - name: Update Maven Coordinates
        run: |
          echo "Updating Maven coordinates..."
          sed -i 's|<version>.*</version>|<version>'$UNIQUE_VERSION'</version>|' pom.xml

      - name: Commit and Push Changes
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          git add .
          git commit -m "Update Maven coordinates for resume"
          git push origin "${{ steps.vars.outputs.BRANCH_NAME }}"

      - name: Change Pull Request State to Draft
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pulls } = await github.rest.pulls.list({
              owner: '${{ github.event.repository.parent.owner.login }}',
              repo: '${{ github.event.repository.parent.name }}',
              head: '${{ github.actor }}:${{ steps.vars.outputs.BRANCH_NAME }}',
              state: 'open'
            });
            if (pulls.length > 0) {
              const prNumber = pulls[0].number;
              await github.rest.pulls.update({
                owner: '${{ github.event.repository.parent.owner.login }}',
                repo: '${{ github.event.repository.parent.name }}',
                pull_number: prNumber,
                draft: true
              });
              console.log(`Pull request #${prNumber} changed back to draft.`);
            } else {
              console.log('No open pull request found.');
            }