name: Publish Artifacts Workflow

run-name: 'Publish Artifacts -- ${{github.event.workflow_run.head_branch}}'

on:
   workflow_run:
    workflows:
      - Build Workflow
    types:
      - completed
        
        
jobs:
  publish-artifacts:
      name: Publish Artifacts
      runs-on: self-hosted
      if: github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'ikmdev'

      env:
        ARTIFACT_REPOSITORY_ID: "maven-snapshots"
        REPOSITORY_NAME: ${{github.repository}}
        BRANCH: "main"
        MAVEN_FILE: '/home/ec2-user/maven/.m2/settings.xml'

      steps:  
        - name: Setup Maven Action
          uses: s4u/setup-maven-action@v1.14.0
          with:
            checkout-fetch-depth: 0
            java-version: 21
            java-distribution: adopt
            maven-version: 3.9.0
        
        - name: Checkout Forked Code Repository
          uses: actions/checkout@v4
          if:   github.event.workflow_run.event == 'pull_request'
          with:
            repository: ${{github.actor}}/${{github.event.repository.name}}
            ref: ${{github.event.workflow_run.head_branch}}
        
        - name: Checkout ikmdev Code Repository
          if:   github.event.workflow_run.event != 'pull_request' && github.event.workflow.name == 'Build Workflow'
          uses: actions/checkout@v4

        - name: Maven Settings File
          uses: whelk-io/maven-settings-xml-action@v22
          with:
              servers: > 
                          [
                            {
                              "id": "nexus"
                            },
                            {
                              "id": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}",
                              "username": "${{ vars.EC2_NEXUS_USERNAME }}",
                              "password": "${{ secrets.EC2_NEXUS_PASSWORD}}"
                            },
                            {
                              "id": "${{vars.NEXUS_MIRROR_ID}}",
                              "username": "${{ vars.EC2_NEXUS_USERNAME }}",
                              "password": "${{ secrets.EC2_NEXUS_PASSWORD}}"
                            }
                          ] 
              profiles: >
                         [{
                              "id": "inject-application-properties",
                              "properties": {
                                  "altSnapshotDeploymentRepository": "${{vars.NEXUS_SNAPSHOT_REPO_ID}}::${{ vars.EC2_NEXUS_URL }}/repository/maven-snapshots",
                                  "altReleaseDeploymentRepository": "${{vars.NEXUS_RELEASE_REPO_ID}}::${{ vars.EC2_NEXUS_URL }}/repository/maven-releases"
                              }
                         }]
              active_profiles: > 
                         [
                            "inject-application-properties"
                         ]
              mirrors: >
                         [{
                             "id": "${{vars.NEXUS_MIRROR_ID}}",
                             "name": "${{vars.NEXUS_MIRROR_ID}}",
                             "url": "${{ vars.EC2_NEXUS_URL }}/repository/maven-public",
                             "mirrorOf": "*"
                         }]
              output_file: .m2/settings.xml


        - name: Deploy To Nexus
          run: |
                   mvn deploy \
                      --batch-mode \
                      -e \
                      -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn \
                      -DskipTests \
                      -DskipITs \
                      -Dmaven.main.skip \
                      -Dmaven.test.skip \
                      -s '/home/ec2-user/actions-runner/_work/${{github.event.repository.name}}/${{github.event.repository.name}}/.m2/settings.xml' \
                      -DrepositoryId='${{env.ARTIFACT_REPOSITORY_ID}}' \
                      -Dgpg.passphrase=${{secrets.GPG_PASSPHRASE}}


  


          
            



  

        