name: Feature Branch Workflow

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select an action: start, finish, or resume'
        required: true
        default: 'start'
        type: choice
        options:
          - start
          - finish
          - resume
      branch_name:
        description: 'Enter the feature branch name (without "feature/")'
        required: true
      unique_version:
        description: 'Enter the unique version number'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  feature_branch_job:
    runs-on: ubuntu-24.04

    steps:
      - name: Run Feature Branch Action
        uses: ikmdev/maven-unique-feature-action/.github/actions/feature-branch-action@main
        with:
          action: ${{ github.event.inputs.action }}
          branch_name: ${{ github.event.inputs.branch_name }}
          unique_version: ${{ github.event.inputs.unique_version }}
